<h1 class="page-header">Админка</h1>
<h2 class="sub-header">Товары</h2>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Название</th>
                <th>Количество</th>
                <th>Цена</th>
                <th>Картинка</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Lorem</td>
                <td>ipsum</td>
                <td>dolor</td>
                <td>sit</td>
                <td>edit</td>
            </tr>
            <tr>
                <td>2</td>
                <td>amet</td>
                <td>consectetur</td>
                <td>adipiscing</td>
                <td>elit</td>
                <td>edit</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Integer</td>
                <td>nec</td>
                <td>odio</td>
                <td>Praesent</td>
                <td>edit</td>
            </tr>
            <tr>
                <td>4</td>
                <td>libero</td>
                <td>Sed</td>
                <td>cursus</td>
                <td>ante</td>
                <td>edit</td>
            </tr>
        </tbody>
    </table>
</div>
